services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"   # ngoài 3000, trong container 80 (nginx)
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
